In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])  # array function is used to create an array

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
len(arr) # len is a function that returns the number of elements in an array

5

In [5]:
arr = np.zeros((5)) # zeros function is used to create an array of zeros
arr

array([0., 0., 0., 0., 0.])

In [6]:
arr = np.ones((5)) # ones function is used to create an array of ones
arr

array([1., 1., 1., 1., 1.])

In [7]:
arr = np.arange(10) # arange function is used to create an array with a range of values
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr = np.linspace(0, 1, 1001) # linspace function is used to create an array with linearly spaced values
arr

array([0.   , 0.001, 0.002, ..., 0.998, 0.999, 1.   ], shape=(1001,))

In [9]:
arr = np.random.rand(5) # random.rand function is used to create an array with random values
arr

array([0.55259966, 0.10860641, 0.12653617, 0.03782935, 0.24419972])

In [10]:
arr = np.random.randn(5) # random.randn function is used to create an array with random values from a normal distribution
arr

array([ 0.3794793 , -0.9339519 , -0.07762532,  0.94123143,  1.32566759])

In [11]:
arr = np.eye(3) # eye function is used to create an identity matrix
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
arr = np.full((5), 17) # full function is used to create an array filled with a specified value
arr

array([17, 17, 17, 17, 17])

In [13]:
arr = np.tile([1, 2, 3], 2) # tile function is used to repeat an array
arr

array([1, 2, 3, 1, 2, 3])

In [14]:
arr = np.repeat([1, 2, 3], 200000) # repeat function is used to repeat elements of an array
arr

array([1, 1, 1, ..., 3, 3, 3], shape=(600000,))

In [15]:
arr = np.reshape(np.arange(25), (5,5)) # reshape function is used to reshape an array
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
# converting 2D array to 1D array
arr = arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr = np.transpose(np.array([[1, 2, 3], [4, 5, 6]])) # transpose function is used to transpose an array
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
arr = np.dot(np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]])) # dot function is used for matrix multiplication
arr

array([[19, 22],
       [43, 50]])

In [19]:
arr = np.linalg.inv(np.array([[1, 2], [3, 4]])) # linalg.inv function is used to compute the inverse of a matrix
arr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [20]:
arr = np.linalg.eig(np.array([[1, 2], [3, 4]])) # linalg.eig function is used to compute the eigenvalues and eigenvectors of a matrix
arr

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [21]:
arr = np.fft.fft(np.array([1, 2, 3, 4])) # fft function is used to compute the one-dimensional discrete Fourier Transform
arr

array([10.+0.j, -2.+2.j, -2.+0.j, -2.-2.j])

In [22]:
arr = np.corrcoef(np.array([1, 2, 3]), np.array([4, 5, 6])) # corrcoef function is used to compute the correlation coefficient matrix
arr

array([[1., 1.],
       [1., 1.]])

In [23]:
arr = np.empty((2, 3)) # empty function is used to create an uninitialized array
arr

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [24]:
arr = np.identity(3) # identity function is used to create an identity matrix
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
x, y = np.meshgrid(np.arange(3), np.arange(3)) # meshgrid function is used to create coordinate matrices
x, y

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]))

In [26]:
arr = np.fromfunction(lambda i, j: i + j, (3, 3)) # fromfunction function is used to construct an array by executing a function over each coordinate
arr

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [27]:
arr = np.fromiter(range(5), dtype=int) # fromiter function is used to create an array from an iterable
arr

array([0, 1, 2, 3, 4])

In [28]:
arr = np.arange(500) # astype function is used to cast an array to a different data type
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [29]:
arr[10 : 20] # slicing an array**-w

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])